task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/k6FracN10LB_mem20K_complexDSP_customSB_22nm/softmax/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/k6FracN10LB_mem20K_complexDSP_customSB_22nm/spree/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/k6FracN10LB_mem20K_complexDSP_customSB_22nm/reduction_layer/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/4bit_adder_double_chain_arch/softmax/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/4bit_adder_double_chain_arch/spree/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/k6FracN10LB_mem20K_complexDSP_customSB_22nm/diffeq2/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/4bit_adder_double_chain_arch/reduction_layer/run002
task_run_dir=/mnt/vault0/cliao43/vtr_cc/vtr-verilog-to-routing/vtr_flow/tasks/chengchieh/4bit_adder_double_chain_arch/diffeq2/run002

4bit_adder_double_chain_arch/diffeq2		OK (took 12.17 seconds, overall memory peak 68.59 MiB consumed by vpr run)
4bit_adder_double_chain_arch/spree		OK (took 12.80 seconds, overall memory peak 73.00 MiB consumed by vpr run)
k6FracN10LB_mem20K_complexDSP_customSB_22nm/spree		OK (took 14.24 seconds, overall memory peak 82.56 MiB consumed by vpr run)
k6FracN10LB_mem20K_complexDSP_customSB_22nm/diffeq2		OK (took 38.76 seconds, overall memory peak 101.31 MiB consumed by vpr run)
4bit_adder_double_chain_arch/reduction_layer		OK (took 285.27 seconds, overall memory peak 401.36 MiB consumed by vpr run)
k6FracN10LB_mem20K_complexDSP_customSB_22nm/reduction_layer		OK (took 330.64 seconds, overall memory peak 311.32 MiB consumed by vpr run)
4bit_adder_double_chain_arch/softmax		OK (took 361.20 seconds, overall memory peak 481.64 MiB consumed by parmys run)
k6FracN10LB_mem20K_complexDSP_customSB_22nm/softmax		OK (took 449.15 seconds, overall memory peak 513.65 MiB consumed by vpr run)
Elapsed time: 449.19 seconds

Parsing test results...
scripts/parse_vtr_task.py -l task_list.dec_2023
Elapsed time: 0.19 seconds
